config/routes.rb
DamavandStar::Application.routes.draw do
  resources :patterns

  resources :brands

  resources :tires

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :tires
  has_many :patterns

end

app/models/pattern.rb
class Pattern < ActiveRecord::Base
  belongs_to :brand
end

app/models/tire.rb
class Tire < ActiveRecord::Base
  belongs_to :brand
  belongs_to :pattern
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  layout 'admin'
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render action: 'show', status: :created, location: @brand }
      else
        format.html { render action: 'new' }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:name, :country, :summary)
    end
end

app/controllers/patterns_controller.rb
class PatternsController < ApplicationController
  before_action :set_pattern, only: [:show, :edit, :update, :destroy]

  # GET /patterns
  # GET /patterns.json
  def index
    @patterns = Pattern.all
  end

  # GET /patterns/1
  # GET /patterns/1.json
  def show
  end

  # GET /patterns/new
  def new
    @pattern = Pattern.new
  end

  # GET /patterns/1/edit
  def edit
  end

  # POST /patterns
  # POST /patterns.json
  def create
    @pattern = Pattern.new(pattern_params)

    respond_to do |format|
      if @pattern.save
        format.html { redirect_to @pattern, notice: 'Pattern was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pattern }
      else
        format.html { render action: 'new' }
        format.json { render json: @pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patterns/1
  # PATCH/PUT /patterns/1.json
  def update
    respond_to do |format|
      if @pattern.update(pattern_params)
        format.html { redirect_to @pattern, notice: 'Pattern was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patterns/1
  # DELETE /patterns/1.json
  def destroy
    @pattern.destroy
    respond_to do |format|
      format.html { redirect_to patterns_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pattern
      @pattern = Pattern.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pattern_params
      params.require(:pattern).permit(:brand_id, :summary)
    end
end

app/controllers/tires_controller.rb
class TiresController < ApplicationController
  before_action :set_tire, only: [:show, :edit, :update, :destroy]

  # GET /tires
  # GET /tires.json
  def index
    @tires = Tire.all
  end

  # GET /tires/1
  # GET /tires/1.json
  def show
  end

  # GET /tires/new
  def new
    @tire = Tire.new
  end

  # GET /tires/1/edit
  def edit
  end

  # POST /tires
  # POST /tires.json
  def create
    @tire = Tire.new(tire_params)

    respond_to do |format|
      if @tire.save
        format.html { redirect_to @tire, notice: 'Tire was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tire }
      else
        format.html { render action: 'new' }
        format.json { render json: @tire.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tires/1
  # PATCH/PUT /tires/1.json
  def update
    respond_to do |format|
      if @tire.update(tire_params)
        format.html { redirect_to @tire, notice: 'Tire was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tire.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tires/1
  # DELETE /tires/1.json
  def destroy
    @tire.destroy
    respond_to do |format|
      format.html { redirect_to tires_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tire
      @tire = Tire.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tire_params
      params.require(:tire).permit(:brand_id, :size, :tire_type, :pattern_id, :year, :week, :summary, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/patterns_helper.rb
module PatternsHelper
end

app/helpers/tires_helper.rb
module TiresHelper
end

app/views/brands/_form.html.erb
<%= form_for(@brand) do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% @brand.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="row">
      <div class="col-sm-5">
          <div class="field">
            <%= f.label 'نام' %><br>
            <%= f.text_field :name , class: 'form-control'%>
          </div>
          <div class="field">
            <%= f.label 'کشور' %><br>
            <%= f.text_field :country , class: 'form-control' %>
          </div>
          <div class="field">
            <%= f.label 'توضیحات' %><br>
            <%= f.text_area :summary , class: 'form-control'%>
          </div><br>
          <div class="actions">
            <%= f.submit class: 'btn btn-default'%>
          </div>
      </div>
    </div>
<% end %>

app/views/brands/edit.html.erb
<h1>ویرایش</h1>

<%= render 'form' %>

<%= link_to 'نمایش', @brand %> |
<%= link_to 'بازگشت', brands_path %>

app/views/brands/index.html.erb
<h1>کارخانه ها</h1>

<table class="table">
  <thead>
    <tr>
      <th>نام</th>
      <th>کشور</th>
      <th>توضیحات</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.name %></td>
        <td><%= brand.country %></td>
        <td><%= brand.summary %></td>
        <td><%= link_to 'Show', brand %></td>
        <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
        <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'افزودن', new_brand_path %>

app/views/brands/new.html.erb
<h2>افزودن تولید کننده جدید</h2>

<%= render 'form' %>
<br>
<%= link_to 'بازگشت', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @brand.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @brand.country %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @brand.summary %>
</p>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>

app/views/layouts/admin.html.erb
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Damavand Star</title>
  <%= stylesheet_link_tag 'application.css','template' , 'bootstrap-rtl.min' , 'rtl' ,'menu' %>
  <%= javascript_include_tag 'application.js', 'bootstrap.min' , 'respond' %>
  <style type="text/css">
      .btn.btn-default        {
          background-color: #990000;
          color: #400;
          border-color:#400 ;
      }
      .btn.btn-primary        {
          background-color: #666;
          color: white;
          border-color:#333 ;
      }
      #search-input{
          background-color: #AAA;
          color: #000;
          border-color:#444 ;
      }
      .dropdown:hover .dropdown-menu {
          display: block;}
  </style>
</head>
<body>
<div class="col-sm-offset-1 col-sm-10">
  <div class="row">
    <nav class="navbar navbar-inverse" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">دماوند استار</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-left">
            <li><a href="#">Link</a></li>
            <form class="navbar-form navbar-left" role="search">
              <div class="form-group">
                <input type="text" class="form-control" id="search-input" placeholder="جستجو">
              </div>
              <button type="submit" class="btn btn-default" >جستجو</button>
            </form>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
    </nav>
  </div>
  <div class="row" >
  </div>
  <div class="row" id="menu-nav">
    <nav class="navbar navbar-menu" role="navigation" >
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">سواری<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Nexen</a></li>
                <li class="divider"></li>
                <li><a href="#">Apollo</a></li>
                <li class="divider"></li>
                <li><a href="#">Ornet</a></li>
              </ul>
            </li>
            <li><a href="#">کامیونی</a></li>
            <li><a href="#">اسپورت</a></li>
            <li><a href="#">زمستانی</a></li>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
    </nav>
  </div>
  <div class="row" id="mainDiv" style="padding-right: 1%;padding-left: 1%;">
      <%= yield %>
  </div>
</div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!doctype html>
<html>
   <head>
      <meta charset="UTF-8">
      <title>Damavand Star</title>
     <%= stylesheet_link_tag 'application.css','template' , 'bootstrap-rtl.min' , 'rtl' ,'menu' %>
     <%= javascript_include_tag 'application.js', 'bootstrap.min' , 'respond' %>
      <style type="text/css">
         .btn.btn-default        {
         background-color: #990000;
         color: #400;
         border-color:#400 ; 
         }
		 .btn.btn-primary        {
         background-color: #666;
         color: white;
         border-color:#333 ; 
         }
         #search-input{
         background-color: #AAA;
         color: #000;
         border-color:#444 ; 
         }
         .dropdown:hover .dropdown-menu {
         display: block;}
      </style>
   </head>
   <body>
      <div class="col-sm-offset-1 col-sm-10">
         <div class="row">
            <nav class="navbar navbar-inverse" role="navigation">
               <div class="container-fluid">
                  <!-- Brand and toggle get grouped for better mobile display -->
                  <div class="navbar-header">
                     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                     <span class="sr-only">Toggle navigation</span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     </button>
                     <a class="navbar-brand" href="#"><%= image_tag 'damavandstarlogo.png',:width => '25px' %> دماوند استار</a>
                  </div>
                  <!-- Collect the nav links, forms, and other content for toggling -->
                  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                     <ul class="nav navbar-nav navbar-left">
                        <li><a href="#">Link</a></li>
                        <form class="navbar-form navbar-left" role="search">
                           <div class="form-group">
                              <input type="text" class="form-control" id="search-input" placeholder="جستجو">
                           </div>
                           <button type="submit" class="btn btn-default" >جستجو</button>
                        </form>
                     </ul>
                  </div>
                  <!-- /.navbar-collapse -->
               </div>
               <!-- /.container-fluid -->
            </nav>
         </div>
         <div class="row" >
         </div>
         <div class="row" id="menu-nav">
            <nav class="navbar navbar-menu" role="navigation" >
               <div class="container-fluid">
                  <!-- Brand and toggle get grouped for better mobile display -->
                  <div class="navbar-header">
                     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                     <span class="sr-only">Toggle navigation</span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     </button>
                  </div>
                  <!-- Collect the nav links, forms, and other content for toggling -->
                  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                     <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                           <a href="#" class="dropdown-toggle" data-toggle="dropdown">سواری<b class="caret"></b></a>
                           <ul class="dropdown-menu">
                              <li><a href="#">Nexen</a></li>
                              <li class="divider"></li>
                              <li><a href="#">Apollo</a></li>
                              <li class="divider"></li>
                              <li><a href="#">Ornet</a></li>
                           </ul>
                        </li>
                        <li><a href="#">کامیونی</a></li>
                        <li><a href="#">اسپورت</a></li>
                        <li><a href="#">زمستانی</a></li>
                     </ul>
                  </div>
                  <!-- /.navbar-collapse -->
               </div>
               <!-- /.container-fluid -->
            </nav>
         </div>
         <div class="row" id="mainDiv">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" style="margin-top:2px;">
               <!-- Indicators -->
               <ol class="carousel-indicators">
                  <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                  <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                  <li data-target="#carousel-example-generic" data-slide-to="2"></li>
               </ol>
               <!-- Wrapper for slides -->
               <div class="carousel-inner">
                  <div class="item active">
                    <%= image_tag 'headimage1.png' , class: 'img-responsive' %>
                     <div class="carousel-caption">
                        Image One
                     </div>
                  </div>
                  <div class="item">
                    <%= image_tag 'headimage2.jpg' , class: 'img-responsive' %>
                     <div class="carousel-caption">
                        Image two
                     </div>
                  </div>
                  <div class="item">
                    <%= image_tag 'headimage3.jpg' , class: 'img-responsive' %>
                     <div class="carousel-caption">
                        Image Three
                     </div>
                  </div>
               </div>
               <!-- Controls -->
               <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev" style="color: #990000">
               <span class="glyphicon glyphicon-chevron-left"></span>
               </a>
               <a class="right carousel-control" href="#carousel-example-generic" data-slide="next" style="color: #990000">
               <span class="glyphicon glyphicon-chevron-right"></span>
               </a>
            </div>
            <div class="row">
               <div class="col-sm-4">
                  <h4 style="color:white">برندها</h4>
                  <ul class="nav nav-stacked" id="popular">
                     <li><a href="#">Nexen</a></li>
                     <li><a href="#">Apollo</a></li>
                     <li><a href="#">Ornet</a></li>
                  </ul>
                  <h4 style="color:white">پر فروش ترین ها</h4>
                  <ul class="nav nav-stacked" id="popular">
                     <li>
                        <div class="row">
                           <div class="col-sm-5"><%= image_tag 'test.png' , class: 'img-responsive' %></div>
                           <div class="col-sm-7">
                              <ul>
                                 <li> نکسن</li>
                                 <li> گل</li>
                                 <li>سایز</li>
                                 <li>قیمت</li>
                              </ul>
                           </div>
                        </div>
                     </li>
                     <li>
                        <div class="row">
                           <div class="col-sm-5"><%= image_tag 'test.png' , class: 'img-responsive' %></div>
                           <div class="col-sm-7">
                              <ul>
                                 <li> نکسن</li>
                                 <li> گل</li>
                                 <li>سایز</li>
                                 <li>قیمت</li>
                              </ul>
                           </div>
                        </div>
                     </li>
                  </ul>
                  <h4 style="color:white">جدیدترین ها</h4>
                  <ul class="nav nav-stacked" id="popular">
                     <li>
                        <div class="row">
                           <div class="col-sm-5"><%= image_tag 'test.png' , class: 'img-responsive' %></div>
                           <div class="col-sm-7">
                              <ul>
                                 <li> نکسن</li>
                                 <li> گل</li>
                                 <li>سایز</li>
                                 <li>قیمت</li>
                              </ul>
                           </div>
                        </div>
                     </li>
                     <li>
                        <div class="row">
                           <div class="col-sm-5"><%= image_tag 'test.png' , class: 'img-responsive' %></div>
                           <div class="col-sm-7">
                              <ul>
                                 <li> نکسن</li>
                                 <li> گل</li>
                                 <li>سایز</li>
                                 <li>قیمت</li>
                              </ul>
                           </div>
                        </div>
                     </li>
                  </ul>
               </div>
               <div class="col-sm-8" style="margin-top: 5px">
                  <ul class="nav nav-tabs">
                     <li class="active"><a href="#">جدید ترین ها</a></li>
                     <li><a href="#">محبوب ترین</a></li>
                     <li><a href="#">جستجوی پیشرفته</a></li>
                  </ul>
                  <div class="row" style="margin-top: 5px">
                     <div class="col-sm-6 col-md-4">
                        <div class="thumbnail">
                          <%= image_tag 'view.png' , class: 'img-responsive' %>
                           <div class="caption">
                              <h3 style="color:#400">Apollo - Amazer</h3>
                              <p>قیمت : ۱،۷۰۰،۰۰۰ ریال</p>
                              <p><a href="#" class="btn btn-default" style="color: white" role="button">خرید</a> <a href="#" class="btn btn-primary"  role="button">مشخصات</a></p>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      </div>
   </body>
</html>

app/views/patterns/_form.html.erb
<%= form_for(@pattern) do |f| %>
  <% if @pattern.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pattern.errors.count, "error") %> prohibited this pattern from being saved:</h2>

      <ul>
      <% @pattern.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brand_id %><br>
    <%= f.text_field :brand_id %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patterns/edit.html.erb
<h1>Editing pattern</h1>

<%= render 'form' %>

<%= link_to 'Show', @pattern %> |
<%= link_to 'Back', patterns_path %>

app/views/patterns/index.html.erb
<h1>Listing patterns</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Summary</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @patterns.each do |pattern| %>
      <tr>
        <td><%= pattern.brand %></td>
        <td><%= pattern.summary %></td>
        <td><%= link_to 'Show', pattern %></td>
        <td><%= link_to 'Edit', edit_pattern_path(pattern) %></td>
        <td><%= link_to 'Destroy', pattern, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pattern', new_pattern_path %>

app/views/patterns/new.html.erb
<h1>New pattern</h1>

<%= render 'form' %>

<%= link_to 'Back', patterns_path %>

app/views/patterns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @pattern.brand %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @pattern.summary %>
</p>

<%= link_to 'Edit', edit_pattern_path(@pattern) %> |
<%= link_to 'Back', patterns_path %>

app/views/tires/_form.html.erb
<%= form_for(@tire) do |f| %>
  <% if @tire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tire.errors.count, "error") %> prohibited this tire from being saved:</h2>

      <ul>
      <% @tire.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brand_id %><br>
    <%= f.text_field :brand_id %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :tire_type %><br>
    <%= f.text_field :tire_type %>
  </div>
  <div class="field">
    <%= f.label :pattern_id %><br>
    <%= f.text_field :pattern_id %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :week %><br>
    <%= f.number_field :week %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tires/edit.html.erb
<h1>Editing tire</h1>

<%= render 'form' %>

<%= link_to 'Show', @tire %> |
<%= link_to 'Back', tires_path %>

app/views/tires/index.html.erb
<h1>Listing tires</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Size</th>
      <th>Tire type</th>
      <th>Pattern</th>
      <th>Year</th>
      <th>Week</th>
      <th>Summary</th>
      <th>Price</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tires.each do |tire| %>
      <tr>
        <td><%= tire.brand %></td>
        <td><%= tire.size %></td>
        <td><%= tire.tire_type %></td>
        <td><%= tire.pattern %></td>
        <td><%= tire.year %></td>
        <td><%= tire.week %></td>
        <td><%= tire.summary %></td>
        <td><%= tire.price %></td>
        <td><%= link_to 'Show', tire %></td>
        <td><%= link_to 'Edit', edit_tire_path(tire) %></td>
        <td><%= link_to 'Destroy', tire, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tire', new_tire_path %>

app/views/tires/new.html.erb
<h1>New tire</h1>

<%= render 'form' %>

<%= link_to 'Back', tires_path %>

app/views/tires/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @tire.brand %>
</p>

<p>
  <strong>Size:</strong>
  <%= @tire.size %>
</p>

<p>
  <strong>Tire type:</strong>
  <%= @tire.tire_type %>
</p>

<p>
  <strong>Pattern:</strong>
  <%= @tire.pattern %>
</p>

<p>
  <strong>Year:</strong>
  <%= @tire.year %>
</p>

<p>
  <strong>Week:</strong>
  <%= @tire.week %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @tire.summary %>
</p>

<p>
  <strong>Price:</strong>
  <%= @tire.price %>
</p>

<%= link_to 'Edit', edit_tire_path(@tire) %> |
<%= link_to 'Back', tires_path %>